### ISSUE TITLE
WB is as likely to kill you as bounce you back

### ISSUE THREAD

**Issue by wingzero54** [CivClassic/WorldBorder#5]
The bounce-back calculations are not very good, and the plugin kills you if it does not successfully find a spot to bounce you back. In practice, players are getting killed on a regular basis by world border (especially as there's no visual world border).

**Comment by Diet-Cola** [comment]
Can fix by updating to: https://github.com/PryPurity/WorldBorder/  

Question is have we done anything special to our repo vs where Pry has continued his branch?

**Comment by Diet-Cola** [comment]
See comment above

**Comment by Diet-Cola** [comment]
Copied the commit from PryPurity where they have fixed the issue into 1.17 stuff

**Comment by wingzero54** [comment]
Fixed with https://github.com/CivClassic/WorldBorder/pull/8
